### ISSUE TITLE
Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

### ISSUE THREAD

**Issue by chenychen** [leafduo/chatgpt-telegram-bot#8]
2023/03/06 11:34:29 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:34:36 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:34:36 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:34:42 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:34:42 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:34:49 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:34:49 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:34:56 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:34:56 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:35:02 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:35:02 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:35:09 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:35:09 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:35:16 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:35:16 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:35:22 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:35:22 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:35:29 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:35:29 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:35:35 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:35:35 Failed to get updates, retrying in 3 seconds...
2023/03/06 11:35:42 Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2023/03/06 11:35:42 Failed to get updates, retrying in 3 seconds...

**Comment by leafduo** [comment]
As the error message says, you should make sure that only one bot instance is running.
