### ISSUE TITLE
复制环境代码，添加到.zshrc里面出现报错 zshrc 118: parse error near `\n'

### ISSUE THREAD

**Issue by YQHan** [leafduo/chatgpt-telegram-bot#9]
**复制环境代码，添加到.zshrc里面出现报错 zshrc 118: parse error near `\n'**  就是第二行tgAPI

**Comment by leafduo** [comment]
Please provide complete file, maybe with sensitive information redacted.

And using `.zshrc` to do this is not a good option, writing a dedicated script or more appropriate.
